package Emloyee;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.boot.Metadata;
import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.registry.StandardServiceRegistry;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;

public class ConnectionMapping {

	public static void main(String[] args) 
	{
		// TODO -Autogenerated method stub
			
		StandardServiceRegistry registry= new StandardServiceRegistryBuilder().configure().build(); // create service
		
		Metadata metadata=new MetadataSources(registry).getMetadataBuilder().build(); // read the info in hibernate .cfg.xml file
		
		SessionFactory sf=metadata.getSessionFactoryBuilder().build(); // connction with database 
		
		Session session=sf.openSession();
		
		Emp e1=new PermanantEmployee("dhananjay","dhananjay@gmail.com", "9881640323", 50000, 7000, 1500,4000);
		Emp e2=new TemporaryEmp("ajya", "Ajay@gmail", "9822076581", 20000,1000, 1500);
		Transaction tr=session.beginTransaction();
		session.save(e1);
		session.save(e2);
		tr.commit();
		System.out.println("saved emp");
		session.close(); // closing session
		sf.close(); //
	}
}
